<?php

/**
 * @file
 * Simple SSE module
 */

/**
 * Implements hook_page_alter().
 */
function simple_sse_page_alter(&$page) {
  $page['content']['#attached']['js'][] = array(
    'data' => array('simple_sse' => array('simpleSSEUrl' => drupal_get_path('module', 'simple_sse') . '/sse.php')),
    'type' => 'setting',
  );
  $page['content']['#attached']['js'][drupal_get_path('module', 'simple_sse') . '/client_js/sse_client.js'] = array('type' => 'file');
  
  dpm($page);
}

/**
 * Implements hook_entity_insert().
 */
function simple_sse_entity_insert($entity, $type) {
  $info = entity_get_info($type);
  
  $idKey = $info['entity keys']['id'];

  $update = array(
    'op' => 'update',
    'type' => $type,
    'id' => $entity->{$idKey},
  );
    
  _simple_sse_send_update($update);
}

/**
 * Implements hook_entity_insert().
 */
function simple_sse_entity_update($entity, $type) {
  $info = entity_get_info($type);
  
  $idKey = $info['entity keys']['id'];

  $update = array(
    'op' => 'update',
    'type' => $type,
    'id' => $entity->{$idKey},
  );
    
  _simple_sse_send_update($update);
}

/**
 * Sends an update to SSE server
 */
function _simple_sse_send_update($update) {
   $resp = drupal_http_request('http://localhost:8080/update', array(
     'method' => 'POST',
     'data' => drupal_http_build_query($update),
     'headers' => array(
       'Content-Type' => 'application/x-www-form-urlencoded'
     )
   ));
}
